### PR TITLE
Adds SetServiceStatus

### PR DESCRIPTION
**Pull request by TomzBench**
This adds a `SetServiceStatus` function which accepts a handle returned by `RegisterServiceCtrlHandlerEx` and a `SERVICE_STATUS` struct. So an additional HSERVICESTATUS handle, a SERVICE_STATUS struct, and SERVICE_STATUS struct associated constants are also added.,

NOTE: I believe the currently implemented `SERVICE_TYPE` constant is a `bitmask` and not an ordinary constant. See the dwServiceType member of the SERVICE_STATUS structure for details

NOTE: I'm not sure why https://github.com/rodrigocfd/winsafe/pull/100 was closed. Please see my comments there and continue here. Unfortunately I lost the nice `#100` number 

Reference:
[1] [SetServiceStatus](https://learn.microsoft.com/en-us/windows/win32/api/winsvc/nf-winsvc-setservicestatus) 
[2] [RegisterServiceCtrlHandlerEx](https://learn.microsoft.com/en-us/windows/win32/api/winsvc/nf-winsvc-registerservicectrlhandlerexw) 
[3] [SERVICE_STATUS](https://learn.microsoft.com/en-us/windows/win32/api/winsvc/ns-winsvc-service_status)

### CODE REVIEW

**Comment by rodrigocfd** [comment]
Hi Tom,

I'm currently implementing [`RegisterServiceCtrlHandlerEx`](https://learn.microsoft.com/en-us/windows/win32/api/winsvc/nf-winsvc-registerservicectrlhandlerexw), which is tricky like all functions which deal with native callbacks. So I must be careful, since it's easy to segfault.

As soon as I finish it, I'll publish it so we can discuss whether it suits your use case. After that, I'll accept your PR, which I believe it will fit nicely together with the code I'm writing.

Thanks for your contribution, we're gonna talk again soon.

**Comment by TomzBench** [comment]
@rodrigocfd Ok sounds good.

I appreciate you taking time to add this feature. 👍

**Comment by TomzBench** [comment]
hello @rodrigocfd 

I was about to start working on adding [RegisterDeviceNotification](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-registerdevicenotificationw) which can be used to register a window handle (or a service) to receive messages of DEV_BROADCAST_HDR. But before doing that I wanted to check in with you and see how this PR was coming along.  

Also I kind of concluded that it was not possible to wrap [ServiceTableEntry](https://learn.microsoft.com/en-us/windows/win32/api/winsvc/ns-winsvc-service_table_entryw) with out doing something abstract, involving macros. There are probably ways you can do it by unnecessarily using the heap, but I was curious if you gave some thought about potentially wrapping this item if potentially supporting the service api's

**Comment by rodrigocfd** [comment]
Hi Tom,

I'm finishing the implementation of `RegisterServiceCtrlHandlerEx`. I was absent for a few days because I'm really busy with work, but I'll return as soon as I can. I'm sorry this is taking longer than usual.

Regarding `SERVICE_TABLE_ENTRY`, is it used solely with `StartServiceCtrlDispatcher`? If so, it's in my backlog. As far as I could see, it's one of those wildly unsafe constructs of Win32, therefore super hard to implement ergonomically in Rust. I'll still think about it, but probably I'll leave the struct with an open pointer – that is, the struct will be unsafe –, then forward the "problem" to `LPSERVICE_MAIN_FUNCTION`.

I'll need your help on all this. If you have good C/C++ examples of `RegisterServiceCtrlHandlerEx` and `StartServiceCtrlDispatcher`, please leave a link to them here. That would help me a lot.

**Comment by TomzBench** [comment]
Here is an [example](https://github.com/zodiacon/Win10SysProgBookSamples) from the author of Win10 sys programing books.  The Chapter19 demonstrates how to use the Service API's pretty well. It is not a real world example however since it is educational book it kind of makes the parts we're looking for more clear.

Per the author, there is some history for why the API is the way it is. Basically in the early days, many services would run under the same process (hence the table array).  Each service would make itself available to be imported as a DLL. The main process would import the service functions and load them into an array and each service would share the same process and save memory.

Modern services typically are implemented as a single entry in the array however. (which could simplify the api significantly i think.)  However, if you want to be a pretty literal translation of the win32 api, and support legacy services to be wrapped, then you would need to support the table array.

I think it is a good idea to leave the "unsafe" function as part of the table.  Technically there is no way around it. Lets say a user wanted to use winsafe to import a bunch of legacy services from DLLs. they would need to manage the raw function handlers themselves.  The most hazardous thing would be to make sure the array is null terminated. To do that with out the heap you might need a macro I think.

**Comment by rodrigocfd** [comment]
That's very interesting.

[AlarmSvc](https://github.com/zodiacon/Win10SysProgBookSamples/tree/master/Chapter19/AlarmSvc) is the most straightforward example, I suppose?

**Comment by TomzBench** [comment]
Yes, the other examples are for creating and removing services which show how sc.exe work

**Comment by rodrigocfd** [comment]
Hi Tom,

Here is my implementation of [`RegisterServiceCtrlHandlerEx`](https://rodrigocfd.github.io/winsafe/winsafe/prelude/trait.kernel_Hservicestatus.html#method.RegisterServiceCtrlHandlerEx). Let me know if this is correct.

**Comment by TomzBench** [comment]
It is very close I think.

**DeviceEvent**

I believe all device events do include the DEV_BROADCAST_HDR so i do not believe it needs to be optional. The DEV_BROADCAST_HDR can be further parsed into:
1. [DevBroadcastDeviceInterface](https://learn.microsoft.com/en-us/windows/win32/api/dbt/ns-dbt-dev_broadcast_deviceinterface_w)
2. [DevBroadcastHandle](https://learn.microsoft.com/en-us/windows/win32/api/dbt/ns-dbt-dev_broadcast_handle)
3. [DevBroadcastOem](https://learn.microsoft.com/en-us/windows/win32/api/dbt/ns-dbt-dev_broadcast_oem)
4. [DevBroadcastPort](https://learn.microsoft.com/en-us/windows/win32/api/dbt/ns-dbt-dev_broadcast_port_w)
5. [DevBroadcastVolume](https://learn.microsoft.com/en-us/windows/win32/api/dbt/ns-dbt-dev_broadcast_volume)

Also, the Interface, Handle, and Port blobs have variable length arrays at the end. Typically it is a name of something, IE: COM1 or something like that.  So they could be heaped with a Guard like is done else where.  The final type for the DeviceEvent could be something like

```rust
pub enum DeviceBroadcastType {
  DeviceInterface(DevBroadcastDeviceInterfaceGuard),
  Handle(DevBroadcastHandleGuard),
  Oem(DEV_BROADCAST_OEM),
  Port(DevBroadcastPortGuard),
  Volume(DEV_BROADCAST_VOLUMN)
}
```

You can make the DeviceEvent tuple look like below.
```rust
DeviceEvent(co::DBT,  DeviceBroadcastType)
```
or
```rust
struct DeviceEvent {
  event: co::DBT,
  type: DeviceBroadcastType
}
```

Note that when you fully describe the blobs (with guards) I think you can get rid of the lifetime.

**PowerEvent**

The POWER_BROADCAST_SETTING only happens when there is a PowerSettingsChange. none of the other PowerEvents include the POWER_BROADCAST_SETTING argument, so i think it misleading to make it optional. It could be enumified similar to the DeviceEvent.

```rust
pub enum PowerEvent {
  PowerStatusChange,
  ResumeAutomatic,
  ResumeSuspend,
  Suspend,
  PowerSettingChange(&'a POWERBROADCAST_SETTING)
}
```
Also the POWERBROADCAST_SETTING can be further parsed into a GUID describing the POWER change. Forexample, if on a laptop and the battery is decreasing, you would get a power event with a GUID of  GUID_BATTERY_PERCENTAGE_REMAINING. And the data field is a u32 between 0-100 representing the battery life...  The data field is different per GUID, so I imagine a final PowerBroadcastSetting type to be a enum as well.

```rust
pub enum PowerBroadcastSetting {
	AcDcPowerSource(co::SYSTEM_POWER_CONDITION),
	BatteryPercentageRemaining(u32),
	ConsoleDisplayState(co::DISPLAY_STATE),
	GlobalUserPresence(co::USER_PRESENCE),
	IdleBackgroundTask,
	MonitorPowerOn(co::MONITOR_STATE),
	PowerSavingStatus(co::POWER_SAVING_STATUS),
	PowerSchemePersonality(co::POWERSCHEME_PERSONALITY),
	SessionDisplayStatus(co::DISPLAY_STATE),
	SessionUserPresence(co::USER_PRESENCE),
	LidSwitchStateChange(co::LIDSWITCH_STATE_CHANGE),
	SystemAwayMode(co::SYSTEM_AWAYMODE),
}
```
Also note that the when fully describing the blob I believe you can also get rid of the lifetime here too.

**SessionChange and TimeChange**

These fields are less important for my use case, however, they are not dynamically lengthed, so the enum can fit the entire parameter in those since the size is fixed. In this case you could also get rid of their lifetimes too.

So concluding I think by fully describing the blobs of data you discover the whole lengths and therefor can remove lifetimes by sticking the known types into the enum (but you need guards for the variable length DEVICE events that describe names of devices).

**Comment by rodrigocfd** [comment]
I uploaded the structs derived from `DEV_BROADCAST_HDR`.

But I'm puzzled about [`DEV_BROADCAST_HANDLE`](https://learn.microsoft.com/en-us/windows/win32/api/dbt/ns-dbt-dev_broadcast_handle). The binary `dbch_data` field is a `BYTE`, but the `dbch_nameoffset` field talks about a string... so is this `BYTE*` always a string?

**Comment by TomzBench** [comment]
I think the dbch_size member gives the length of the data as it gives the length of the whole structure, including the data. The name_offset seems like an index to a string within the data. I haven't found how it is used though. Seems strange.

**Comment by rodrigocfd** [comment]
Hi Tom,

I wrote an implementation for the `RegisterServiceCtrlHandlerEx` enum argument, does it look good?

The `POWEREVENT` stuff is not there yet, but if everything is fine so far, it will be the next one I'll tackle.

**Comment by TomzBench** [comment]
@rodrigocfd I think so far it looks pretty good.  As far as DEV_BROADCAST_HANDLE goes, somebody can raise issue if they ever need to parse the dbch_data field. Likely if a person needs to parse the dbch_data field they'll be in a position to understand it better. So the DeviceEvent looks fairly complete as far as I can tell.

Also my previous thoughts about getting rid of the lifetime is good to ignore, I think it is more correct how you have it because there is no need to copy these bytes.

**Comment by rodrigocfd** [comment]
Hi Tom,

I implemented the power event stuff, could you please take a look?

**Comment by TomzBench** [comment]
@rodrigocfd 

I think the API distinguishes "Monitor" state from "Display" state, where Display can be tri positioned as on/off/dimmed. and the "Monitor" state is either on or off.  So you could probably replace the MonitorPowerOn enum member with a bool as similar to as you did for the PowerSavingsStatus.  So reusing the co::MONITOR_DISPLAY_STATE is (maybe) subtly inaccurate because it implies the MonitorPowerOn can be dimmed.

(Maybe it can be though - who knows what windows will stick in there - so perhaps your experience with windows is handing perhaps undocumented but probable behavior ::shrug::)

I think i'll be able to have have more valuable feedback when I am able to start using it though.

Thank you for the update.

**Comment by rodrigocfd** [comment]
I guided myself through the Windows headers. The [`MONITOR_DISPLAY_STATE`](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/ne-wdm-_monitor_display_state) does exist, but not a constant with just the off/on values. My guess is they simply reused the values without taking care about an invalid state for MonitorPowerOn, so in order be more accurate, we must diverge a little.

I made a small change, and now MonitorPowerOn is just a `bool`, which seems reasonable to me.

Do you think I can merge your commits now? If so, I need you to resolve the conflicts.

Anyway, even if you're not 100% sure of the implementation now, we can change some stuff in the future, when you really start using it. No problem.

**Comment by TomzBench** [comment]
@rodrigocfd I merged master and resolved conflicts.  The 3 commits are the original commit, rebasing with master to fix conflicts, and then updating the readme numbers.

Its hard to squash it all into 1 commit because there is a conflict with each README on each commit so rebasing is difficult im not sure best way to squash these.

**Comment by TomzBench** [comment]
When implementing a service, a lot of the preferable API's do not use window handles.  For example, NamedPipes, and CreateWaitableTimer to name some i need. So if interested I could add those. They should not be no where near as difficult as the Svc api so it should go easier.

can try in a seperate PR unless you have some thoughts against adding NamedPipes or waitable timers.

**Comment by TomzBench** [comment]
@rodrigocfd 

Any thoughts on [StartServiceCtrlDispatcher](https://learn.microsoft.com/en-us/windows/win32/api/winsvc/nf-winsvc-startservicectrldispatchera)?

It accepts a Null terminated array of Name/Proc. And to make more complicated, the name cannot be static inside the struct, and must point to a string outside of the struct.  See its initialization here:

```c
int main() {
  WCHAR name[] = L"foo";
  const SERVICE_TABLE_ENTRY table [] = {
    {name, proc},
    { nullptr, nullptr}
  }
  ::StartServiceCtrlDispatcher(table);
}
```
Notice how `name` cannot be statically created inside the table.

I know the goals are not to provide over abstraction over the windows API. So im curious what the api would look like.

In order to avoid heap allocations and keep simple i kind of like a macro approach which could handle the details of null terminating the table and setting up the name of the service.  something like this:

```rust
extern "system" fn service_main(nArgs: u32, args: *mut OsStr) { /* */ }

fn main() {
  winsafe::start_service_ctrl_dispatcher![
    "MyService", service_main
  ];
}
```

I haven't attempted that though as its fairly opinionated approach i think - maybe you know another way to do it more inline with the normal winsafe api's.

Inside the service_main is where you register the control handler and set service status, which would i think complete the Service Api.

**Comment by rodrigocfd** [comment]
> When implementing a service, a lot of the preferable API's do not use window handles. For example, NamedPipes, and CreateWaitableTimer to name some i need. So if interested I could add those. They should not be no where near as difficult as the Svc api so it should go easier.
> 
> can try in a seperate PR unless you have some thoughts against adding NamedPipes or waitable timers.

I need more info on this. Create a PR or an issue with your proposal, and let's discuss the idea.

> Any thoughts on [StartServiceCtrlDispatcher](https://learn.microsoft.com/en-us/windows/win32/api/winsvc/nf-winsvc-startservicectrldispatchera)?

An arbitrary array of callbacks looks tricky... I'll need to think about what can be done in such situation.

**Pull request merged**
