### PR TITLE
Add ChangeDisplaySettingsEx to Safe Functions

### PR DESCRIPTION
**Pull request by amithkk**
Implements #20

### CODE REVIEW

**Comment by michidk** [comment]
Tested your branch and works great! Is there anything blocking this from getting merged?

**Comment by amithkk** [comment]
@michidk nope, there's nothing blocking it from a merge, feel free to :)

**Comment by rodrigocfd** [comment]
Sorry for taking too long, I'm changing other things that would potentially conflict with this change. I'll try to stash my changes and accept this one first.

**Comment by michidk** [comment]
Hey @amithkk ,
you also have a branch where you implemented [EnumDisplayDevices](https://github.com/amithkk/winsafe/commit/f1814133163b5dd1b33b60373245baa22e3dc26f#diff-aac5b0beab4954ca6eff4e9b860119ec0d3e972a88f3d59915f71bb877102de3R124). I just tested it as well and it works great.
Could you please create a PR for that?

**Comment by amithkk** [comment]
@rodrigocfd No problem, thank you for the excellent library 😄

**Comment by amithkk** [comment]
@michidk Sure, would be happy to. Might have to rebase and create the corresponding issue so will get to that shortly

**Pull request merged**
