### PR TITLE
Load accelerators from the resource file

### PR DESCRIPTION
**Pull request by rosscanning**
Support loading of accelerators from the resource file, rather than manual creation using `CreateAcceleratorTable()`

### CODE REVIEW

**Comment by rodrigocfd** [comment]
This function [already exists](https://rodrigocfd.github.io/winsafe/winsafe/prelude/trait.user_Hinstance.html#method.LoadAccelerators).

**Comment by rosscanning** [comment]
Hi @rodrigocfd,

> This function already exists.

True, but it returns `HACCEL`, not `DestroyAcceleratorTableGuard`. Currently my code looks like this:

```
    let accel_table = HINSTANCE::NULL.LoadAccelerators(w::IdStr::Id(123)).unwrap();
    let wnd = gui::WindowMain::new(gui::WindowMainOpts {
        accel_table: Some(unsafe { DestroyAcceleratorTableGuard::new(accel_table) }),
        ..Default::default()
    });

```
Is there a way of doing this without unsafe code?

**Comment by rodrigocfd** [comment]
I didn't implement it because, according to [the documentation](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-loadacceleratorsw):

> Accelerator tables loaded from resources are freed automatically when the application terminates.

Do you have an use case where this won't apply?

**Comment by rosscanning** [comment]
It doesn't matter if DestroyAcceleratorTable() gets called on my accelerator table or not. Like you say, it'll get freed when the app terminates.

I just need to be able to pass my accelerator table, for which I only have an HACCEL, to WindowMainOpts. WindowMainOpts only accepts DestroyAcceleratorTableGuard, not HACCEL. So I need to convert my HACCEL to a DestroyAcceleratorTableGuard. Unless there's some other way?

**Comment by rodrigocfd** [comment]
> WindowMainOpts only accepts DestroyAcceleratorTableGuard, not HACCEL

Yes, that's a valid use case I didn't notice.

But instead of having the same function implemented in two different places, make another PR changing the return value of `LoadAccelerators`, so it always return a `DestroyAcceleratorTable`. The I'll merge your PR.

**Pull request closed without merging**
