### PR TITLE
WIP: Add IPersistFile interface, and windows shortcut helper utility (Lnk)

### PR DESCRIPTION
**Pull request by caesay**
**This should not be merged without fixes below.**

I don't really know my way around Rust yet (still learning) or COM (never did), but I tried to add support for IPersistFile with the ultimate goal of being able to create/read shortcuts on windows. 

There are a few rust crates that already try to do this (lnk-rs, mslnk) but they try and achieve this by directly editing .lnk files instead of COM interop. This has advantages and disadvantages. The advantage is, that you can create these files when not on Windows. The disadvantages are many, but overall it is complex, and these libraries are incomplete and have bugs. 

I think it would be advantageous for this library to have an official Microsoft-approved solution to managing shortcuts on windows. 

The implementation was working at one point, but now it does not appear to work. I do not know what I did to break it, and did not have the "working" iteration checked in to source code unfortunately. The problem is a nondescript COM error (either Invalid method or The parameter is incorrect). I believe this is because I have created the IPersistFile VTable incorrectly, but I have tried a bunch of variations and I can't seem to get it working again. 

So I'm leaving this with you. If you can spot the problem and would like me to fix it, I will - otherwise you can fix / merge or just close this. Thanks either way!

Additionally, I would love to add the ability to read and write the AppModelID and ToastActivatorCLSID, but this is more complex. It requires converting the IShellLink to an IPropertyStore and then setting PKEY_AppUserModel_ToastActivatorCLSID or PKEY_AppUserModel_ID to a String PropVariant. Unfortunately, the PropVariant contained in Winsafe does not yet seem to support strings and I was not sure how to add that.

### CODE REVIEW

**Comment by rodrigocfd** [comment]
> and windows shortcut helper utility (Lnk)

I don't think this is a good idea. If we start adding utilities for everything, soon we would have a very polluted library. If you really need such utility, it's better create a separated, specific project with WinSafe as a dependency.

> I believe this is because I have created the IPersistFile VTable incorrectly,

I really don't see anything wrong with it... could you show me an usage example, so I can debug it?

**Comment by caesay** [comment]
> I don't think this is a good idea. If we start adding utilities for everything, soon we would have a very polluted library. If you really need such utility, it's better create a separated, specific project with WinSafe as a dependency.

No worries, I thought there was good precedent because of the "task_dlg" utility which already exists, should that also be broken out into a new library?

 > could you show me an usage example, so I can debug it?

It did work at one point, and then I cleaned up the IPersistFile file, following the example of the other interfaces there, and then it stopped working - and I did not have the previous version checked in. I spent many hours trying to resolve this :)

The usage example I can provide is the Lnk helper in this PR.

```rust
let lnk = Lnk::create_new();
lnk.set_path(r"C:\path\to\some\file.exe");
lnk.save_as(r"C:\path\to\new\shortcut.lnk");
```

Or the equivalent, reading an existing shortcut with `Lnk::open_read` or `Lnk::open_write`.

**Comment by rodrigocfd** [comment]
> No worries, I thought there was good precedent because of the "task_dlg" utility which already exists, should that also be broken out into a new library?

Actually `task_dlg` should never have existed, but [`TaskDialogIndirect`](https://learn.microsoft.com/en-us/windows/win32/api/commctrl/nf-commctrl-taskdialogindirect) API is so horrible, and so commonly used, that I had to implement something to ease the pain. I have an idea for a better version though, so I'll soon get rid of `task_dlg`.

> I spent many hours trying to resolve this :)

I believe in you. I tried the following code, and it worked 100%:

```rust
use winsafe::{self as w, prelude::*, co};

fn main() {
	let _com_lib = w::CoInitializeEx(
		co::COINIT::APARTMENTTHREADED | co::COINIT::DISABLE_OLE1DDE,
	).unwrap();

	let sh_lnk = w::CoCreateInstance::<w::IShellLink>(
		&co::CLSID::ShellLink,
		None,
		co::CLSCTX::INPROC_SERVER,
	).unwrap();
	sh_lnk.SetPath(r"C:\Users\Rodrigo\Desktop\my file.txt").unwrap();

	let per_f = sh_lnk.QueryInterface::<w::IPersistFile>().unwrap();
	per_f.Save(Some(r"C:\Users\Rodrigo\Desktop\my link.lnk"), true).unwrap();
}
```

My `IPersistFile` implementation is the same as yours, with minor changes:

```rust
#![allow(non_camel_case_types, non_snake_case)]

use crate::co;
use crate::decl::*;
use crate::kernel::ffi_types::*;
use crate::ole::privs::*;
use crate::prelude::*;
use crate::vt::*;

/// [`IPersistFile`](crate::IPersistFile) virtual table.
#[repr(C)]
pub struct IPersistFileVT {
	pub IPersistVT: IPersistVT,
	pub IsDirty: fn(COMPTR) -> HRES,
	pub Load: fn(COMPTR, PCSTR, u32) -> HRES,
	pub Save: fn(COMPTR, PCSTR, i32) -> HRES,
	pub SaveCompleted: fn(COMPTR, PCSTR) -> HRES,
	pub GetCurFile: fn(COMPTR, PVOID) -> HRES,
}

com_interface! { IPersistFile: "0000010b-0000-0000-c000-000000000046";
	/// [`IPersistFile`](https://learn.microsoft.com/en-us/windows/win32/api/objidl/nn-objidl-ipersistfile)
	/// COM interface over [`IPersistFileVT`](crate::vt::IPersistFileVT).
	///
	/// Automatically calls
	/// [`Release`](https://learn.microsoft.com/en-us/windows/win32/api/unknwn/nf-unknwn-iunknown-release)
	/// when the object goes out of scope.
}

impl ole_IPersist for IPersistFile {}
impl ole_IPersistFile for IPersistFile {}

/// This trait is enabled with the `ole` feature, and provides methods for
/// [`IPersistFile`](crate::IPersistFile).
///
/// Prefer importing this trait through the prelude:
///
/// ```no_run
/// use winsafe::prelude::*;
/// ```
pub trait ole_IPersistFile: ole_IUnknown {
	/// [`IPersistFile::IsDirty`](https://learn.microsoft.com/en-us/windows/win32/api/objidl/nf-objidl-ipersistfile-isdirty)
	/// method.
	#[must_use]
	fn IsDirty(&self) -> HrResult<bool> {
		okfalse_to_hrresult(
			unsafe { (vt::<IPersistFileVT>(self).IsDirty)(self.ptr()) },
		)
	}

	/// [`IPersistFile::Load`](https://learn.microsoft.com/en-us/windows/win32/api/objidl/nf-objidl-ipersistfile-load)
	/// method.
	fn Load(&self, file_name: &str, dw_mode: co::STGM) -> HrResult<()> {
		ok_to_hrresult(
			unsafe {
				(vt::<IPersistFileVT>(self).Load)(
					self.ptr(),
					WString::from_str(file_name).as_ptr(),
					dw_mode.raw(),
				)
			},
		)
	}

	/// [`IPersistFile::Save`](https://learn.microsoft.com/en-us/windows/win32/api/objidl/nf-objidl-ipersistfile-save)
	/// method.
	fn Save(&self, file_name: Option<&str>, remember: bool) -> HrResult<()> {
		ok_to_hrresult(
			unsafe {
				(vt::<IPersistFileVT>(self).Save)(
					self.ptr(),
					file_name.map_or(std::ptr::null(), |f| WString::from_str(f).as_ptr()),
					remember as _,
				)
			},
		)
	}
}
```

I didn't test your wrapper, so I guess the error is there.

**Comment by caesay** [comment]
The code for creating a link you shared works using your IPersistFile, yes, but the following (to resolve a link) does not.

```rust
    let link_path = r"C:\your\link.lnk";
    let _comguard = w::CoInitializeEx(co::COINIT::APARTMENTTHREADED | co::COINIT::DISABLE_OLE1DDE)?;
    let me = w::CoCreateInstance::<w::IShellLink>(&co::CLSID::ShellLink, None, co::CLSCTX::INPROC_SERVER)?;
    let pf = me.QueryInterface::<w::IPersistFile>()?;
    pf.Load(link_path, co::STGM::READ)?;
    me.Resolve(&w::HWND::NULL, co::SLR::NO_UI)?;
    let path = me.GetPath(None, co::SLGP::UNCPRIORITY)?;
```

Resolve() returns an Err with a generic "Incorrect function" error. There is some documentation for resolving links here: https://learn.microsoft.com/en-us/windows/win32/shell/links

This same code in C++ works fine. So maybe the issue is with the IShellLink VTable?

```cpp
#include <iostream>
#include "windows.h"
#include "shobjidl.h"
#include "shlguid.h"

int main()
{
    auto link_path = L"C:\\Users\\Caelan\\Desktop\\testclowd123hi.lnk";
    CoInitializeEx(NULL, COINIT_APARTMENTTHREADED | COINIT_DISABLE_OLE1DDE);
    IShellLink* psl;
    IPersistFile* ppf;
    CoCreateInstance(CLSID_ShellLink, NULL, CLSCTX_INPROC_SERVER, IID_IShellLink, (LPVOID*)&psl);
    psl->QueryInterface(IID_IPersistFile, (void**)&ppf);
    ppf->Load(link_path, STGM_READ);
    psl->Resolve(NULL, SLR_NO_UI);
    wchar_t szGotPath[MAX_PATH];
    auto path = psl->GetPath(szGotPath, MAX_PATH, NULL, SLGP_UNCPRIORITY);
}
```

**Comment by rodrigocfd** [comment]
> The code for creating a link you shared works using your IPersistFile, yes, but the following (to resolve a link) does not.
> 
> ```rust
>     let link_path = r"C:\your\link.lnk";
>     let _comguard = w::CoInitializeEx(co::COINIT::APARTMENTTHREADED | co::COINIT::DISABLE_OLE1DDE)?;
>     let me = w::CoCreateInstance::<w::IShellLink>(&co::CLSID::ShellLink, None, co::CLSCTX::INPROC_SERVER)?;
>     let pf = me.QueryInterface::<w::IPersistFile>()?;
>     pf.Load(link_path, co::STGM::READ)?;
>     me.Resolve(&w::HWND::NULL, co::SLR::NO_UI)?;
>     let path = me.GetPath(None, co::SLGP::UNCPRIORITY)?;
> ```

The code above works 100% for me.

Are you pointing directly to the GitHub repo, to get the latest commits?

```
[dependencies]
winsafe = { git = "https://github.com/rodrigocfd/winsafe", features = [] }
```

**Comment by caesay** [comment]
The issue was unrelated, Resolve() error's on links which have missing targets. Sorry for taking up your time. Since master does not yet have IPersistFile, I'll open a new PR for that.

**Pull request closed without merging**
